# Generated by Django 5.2.3 on 2025-07-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0002_alter_support_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Support.support')),
            ],
        ),
    ]
